services:
  - type: web
    name: video-generator
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
